# Kimberly D's Informatics Projects Site

![](https://github.com/Kimist99/kimberlyd.github.io/blob/master/assets/img/healthDataSciAtGWFeb2020.jpg?raw=true)

## About Kimberly D 

Kimberly is a Chemical and Health Informaticist currently finishing her PhD in Health Informatics. She’s the co-founder of [BlackTIDES](https://blacktidesdata.com/) an organization created to support future and current Black Data Professionals and she also works as a Data Educator. Her research interests are in HIV Health Disparities using AI/Machine Learning.


![](https://github.com/Kimist99/kimberlyd.github.io/blob/master/assets/img/chemInfopic.jpeg?raw=true)

## Data Analytics Projects / Websites

- [Tableu Public](https://public.tableau.com/app/profile/kimberly.d6305)
- [30 Days of Code - 2020](https://github.com/Kimist99/DataKimist_30_Days_Of_Code)

## License

GNU General Public License v3.0
