title: Hello, world! I'm Kimberly D!
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/kimberlyd" # the subpath of your site, e.g. /blog
url: "https://github.com/Kimist99.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Kimberly D
author-img: KimNYC21_copy.jpg # add your photo
about-author: I'm a Chemical and Health Informaticist, Data Science Consultant and Educator, and PhD Candidate in Health Informatics
social-twitter: @DataKimist
social-github: Kimist99
social-linkedin: https://www.linkedin.com/in/kimberly-d-b0570737/
social-email: Kimist99@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
